version: "3.8"
services:
  website:
    build: ./website
    ports:
      - 8000:8000
    depends_on:
      - cars_api

    networks:
      - webnet
  cars_api:
    build: ./cars_api
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    networks:
      - webnet
  db:
    build: ./db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: hello
    networks:
      - webnet

networks:
  webnet:
