version: "3.8"
services:
  cars_api:
    build:
      context: ./cars_api
      #target: development
    volumes:
      - .:/usr/local/api
      - /usr/local/api/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    networks:
      - webnet

networks:
  webnet:
