version: "3.8"
services:
  cars_website:
    build:
      context: ./cars_website
      #target: development
    ports:
      - 4200:80/tcp
    volumes:
      - .:/usr/local/app
      - /usr/local/app/node_modules
    networks:
      - webnet
  cars_api:
    build:
      context: ./cars_api
      #target: development
    volumes:
      - .:/usr/local/api
      - /usr/local/api/node_modules
    ports:
      - 3000:3000
    # depends_on:
    #   - db
    environment:
      DB_HOST: db
    networks:
      - webnet

  db:
    build: ./db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: hello
    networks:
      - webnet

networks:
  webnet:
